/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minitienda_isabelladubon.GUI;

import minitienda_isabelladubon.Usuario;

/**
 *
 * @author miria
 */
public class FinJuego extends javax.swing.JPanel {
    private Main mainFrame;
    private Usuario seleccion;
    private PantallaMain principal;
    /**
     * Creates new form FinJuego
     */
    public FinJuego(Main mainFrame, PantallaMain principal, Usuario seleccion) {
        initComponents();
        this.mainFrame = mainFrame;
        this.seleccion = seleccion;
        this.principal = principal;
        String dinero = Double.toString(this.seleccion.getDinero());
        dineroRecaudado.setText(dinero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dineroRecaudadoTxt = new javax.swing.JLabel();
        volverAEmpezar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dineroRecaudado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 117, 132));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/descarga (12) (1).jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 133, -1, -1));

        jLabel2.setFont(new java.awt.Font("Jokerman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 1, 1));
        jLabel2.setText("¡ FELICIDADES !");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 27, 412, 73));

        dineroRecaudadoTxt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        dineroRecaudadoTxt.setForeground(new java.awt.Color(60, 1, 1));
        dineroRecaudadoTxt.setText("Dinero recaudado: L.");
        add(dineroRecaudadoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 300, 40));

        volverAEmpezar.setBackground(new java.awt.Color(60, 1, 1));
        volverAEmpezar.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        volverAEmpezar.setForeground(new java.awt.Color(255, 255, 204));
        volverAEmpezar.setText("<html> Volver a <p> empezar >>");
        volverAEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverAEmpezarActionPerformed(evt);
            }
        });
        add(volverAEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 50));

        jPanel2.setBackground(new java.awt.Color(211, 55, 49));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 10, 450));

        jPanel3.setBackground(new java.awt.Color(253, 202, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 10, -1));

        jPanel4.setBackground(new java.awt.Color(145, 216, 200));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 10, -1));

        jPanel5.setBackground(new java.awt.Color(211, 55, 49));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(211, 55, 49));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(145, 216, 200));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jPanel7.setBackground(new java.awt.Color(253, 202, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(211, 55, 49));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 1, 1));
        jLabel4.setText("<html> Has terminado los 7 dias en la <p> Mini Tienda de Sweet Flame! <html>");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 248, 177));

        dineroRecaudado.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        dineroRecaudado.setForeground(new java.awt.Color(60, 1, 1));
        dineroRecaudado.setText("100");
        add(dineroRecaudado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void volverAEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverAEmpezarActionPerformed
        seleccion.setDinero(0.0);
        seleccion.setDiaEnJuego(0);
        seleccion.getFacturas().clear();
        seleccion.vaciarHistorial();
        mainFrame.MostrarPanel(principal);
        mainFrame.avanzarASiguienteCliente();
    }//GEN-LAST:event_volverAEmpezarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dineroRecaudado;
    private javax.swing.JLabel dineroRecaudadoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton volverAEmpezar;
    // End of variables declaration//GEN-END:variables
}
