/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minitienda_isabelladubon.GUI;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import minitienda_isabelladubon.Usuario;
import minitienda_isabelladubon.GUI.PantallaMain;
import minitienda_isabelladubon.GestorPedido;
import minitienda_isabelladubon.Pedido;
import minitienda_isabelladubon.Producto;
import java.util.Random;

/**
 *
 * @author miria
 */
public class Main extends javax.swing.JFrame {
    Random random = new Random();
    private ArrayList<Usuario> usuariosLista;
    private GestorPedido gestor = new GestorPedido();
    private Usuario seleccion; 
    private String diaUser;
    private String dineroUser;
    private Producto[] tienda;
    PantallaMain principal;
    PantallaPedido pedidos;
    private int numPedido = 1;
    private Pedido pedidoActual;
    private int contClientes = 0;
    private int maxClientes = random.nextInt(3, 6);

    /**
     * Creates new form Main
     */
    
    public Main(ArrayList<Usuario> listaUsuarios, Usuario seleccion, Producto[] tienda) {
        initComponents();
        this.tienda = tienda;
        this.seleccion = seleccion;
        this.usuariosLista = listaUsuarios;
        
        //muestra el nombre de usuario 
        usuarioNombre.setText(seleccion.getNombre());
        
        //muestra el dia del usuario en el JLabel
        int d = seleccion.getDiaEnJuego();
        diaUser = Integer.toString(d);
        usuarioDiaLbl.setText(diaUser);
        
        //muestra el dinero del usuario en el JLabel
        double m = seleccion.getDinero();
        dineroUser = Double.toString(m);
        usuarioDineroLbl.setText(dineroUser);
        principal = new PantallaMain(tienda, seleccion, this);
        pedidos = new PantallaPedido(tienda, seleccion, principal, this);
        setDefaultCloseOperation(ElegirUser.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pedidoBtn = new javax.swing.JButton();
        principalBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        subTitulo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        subTitulo1 = new javax.swing.JLabel();
        divisor = new javax.swing.JLabel();
        Nivel = new javax.swing.JPanel();
        usuarioNombre = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        usuarioDiaLbl = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        usuarioDineroLbl = new javax.swing.JLabel();
        lempiras = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setForeground(new java.awt.Color(254, 253, 235));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 117, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        pedidoBtn.setBackground(new java.awt.Color(60, 1, 1));
        pedidoBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        pedidoBtn.setForeground(new java.awt.Color(255, 255, 204));
        pedidoBtn.setText("Pedido");
        pedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoBtnActionPerformed(evt);
            }
        });

        principalBtn.setBackground(new java.awt.Color(60, 1, 1));
        principalBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        principalBtn.setForeground(new java.awt.Color(255, 255, 204));
        principalBtn.setText("Principal");
        principalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pedidoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(principalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(pedidoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(principalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 450));

        jPanel2.setBackground(new java.awt.Color(145, 216, 200));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel2.setForeground(new java.awt.Color(145, 216, 200));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        subTitulo2.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        subTitulo2.setForeground(new java.awt.Color(211, 55, 49));
        subTitulo2.setText("Simulador");

        titulo.setFont(new java.awt.Font("Bodoni MT Black", 3, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(211, 55, 49));
        titulo.setText("Sweet Flame");

        subTitulo1.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        subTitulo1.setForeground(new java.awt.Color(211, 55, 49));
        subTitulo1.setText("Mini Tienda");

        divisor.setFont(new java.awt.Font("Bodoni MT Black", 3, 55)); // NOI18N
        divisor.setForeground(new java.awt.Color(248, 117, 132));
        divisor.setText("|");

        Nivel.setBackground(new java.awt.Color(253, 202, 51));
        Nivel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        usuarioNombre.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        usuarioNombre.setForeground(new java.awt.Color(211, 55, 49));
        usuarioNombre.setText("USUARIO");
        usuarioNombre.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(211, 55, 49));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        usuarioDiaLbl.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 48)); // NOI18N
        usuarioDiaLbl.setForeground(new java.awt.Color(60, 1, 1));
        usuarioDiaLbl.setText("1");

        dia.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 48)); // NOI18N
        dia.setForeground(new java.awt.Color(60, 1, 1));
        dia.setText("DIA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuarioDiaLbl)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioDiaLbl)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dinero.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        dinero.setForeground(new java.awt.Color(211, 55, 49));
        dinero.setText("Dinero:");

        usuarioDineroLbl.setFont(new java.awt.Font("OCR A Extended", 0, 20)); // NOI18N
        usuarioDineroLbl.setForeground(new java.awt.Color(211, 55, 49));
        usuarioDineroLbl.setText("0.0");

        lempiras.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        lempiras.setForeground(new java.awt.Color(211, 55, 49));
        lempiras.setText("L.");

        javax.swing.GroupLayout NivelLayout = new javax.swing.GroupLayout(Nivel);
        Nivel.setLayout(NivelLayout);
        NivelLayout.setHorizontalGroup(
            NivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NivelLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(NivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NivelLayout.createSequentialGroup()
                                .addComponent(lempiras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usuarioDineroLbl)
                                .addGap(12, 12, 12))
                            .addComponent(dinero, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NivelLayout.createSequentialGroup()
                        .addComponent(usuarioNombre)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        NivelLayout.setVerticalGroup(
            NivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NivelLayout.createSequentialGroup()
                .addComponent(usuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NivelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NivelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dinero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(NivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lempiras)
                            .addComponent(usuarioDineroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTitulo1)
                    .addComponent(subTitulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(titulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(subTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTitulo2))
                    .addComponent(divisor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 150));

        contenido.setLayout(new java.awt.CardLayout());
        jPanel4.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 720, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoBtnActionPerformed
        MostrarPanel(pedidos);
    }//GEN-LAST:event_pedidoBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        regenerarPedido(seleccion, tienda, numPedido);
        principal.setPedido(this.pedidoActual);
        pedidos.setPedido(this.pedidoActual);
        pedidos.setGestorPedidos(gestor);
        principal.setTienda(tienda);
        principal.setSeleccion(seleccion);
        principal.alAbrirMain();
        MostrarPanel(principal);
    }//GEN-LAST:event_formWindowOpened

    private void principalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalBtnActionPerformed
        MostrarPanel(principal);
    }//GEN-LAST:event_principalBtnActionPerformed

    public void MostrarPanel(JPanel panel){
        contenido.removeAll();
        panel.setSize(720, 450);
        panel.setLocation(0, 0);
        contenido.add(panel);
        contenido.revalidate();
        contenido.repaint();
    }
    
    public void actualizarDia (){
        int dia = seleccion.getDiaEnJuego();
        String diaCadena = Integer.toString(dia);
        usuarioDiaLbl.setText(diaCadena);
    }
    
    public int getNumPedido(){
        return this.numPedido;
    }
    
    public void regenerarPedido(Usuario usuario, Producto[] tienda, int numPedido){
        if (this.gestor != null) {
            Pedido nuevoPedido = this.gestor.generarPedido(usuario, tienda, numPedido);
            this.pedidoActual = nuevoPedido; 
        }
    }
    
    public void avanzarASiguienteCliente() {
        this.numPedido++;
        this.contClientes++;
    
        this.regenerarPedido(this.seleccion, this.tienda, this.numPedido); 
        this.principal.setPedido(this.pedidoActual); 
        this.pedidos.setPedido(this.pedidoActual);
        this.pedidos.resetNuevoCliente();
        this.principal.alAbrirMain();
        if (this.contClientes == this.maxClientes) {
            this.principal.getBotonNextCliente().setVisible(false);
        } else {
            this.principal.getBotonNextCliente().setVisible(true); 
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nivel;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel dia;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel divisor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lempiras;
    private javax.swing.JButton pedidoBtn;
    private javax.swing.JButton principalBtn;
    private javax.swing.JLabel subTitulo1;
    private javax.swing.JLabel subTitulo2;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel usuarioDiaLbl;
    private javax.swing.JLabel usuarioDineroLbl;
    private javax.swing.JLabel usuarioNombre;
    // End of variables declaration//GEN-END:variables
}
