/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minitienda_isabelladubon.GUI;

import java.util.ArrayList;
import javax.swing.JLabel;
import minitienda_isabelladubon.Producto;

/**
 *
 * @author miria
 */
public class PantallaPedido extends javax.swing.JPanel {
    private Producto[] tienda;
    private ArrayList<Producto> productos;
    private ArrayList<Integer> cantidades;
    private int cantPies = 0;
    private int cantPinias = 0;
    private int cantGoms = 0;
    private int cantPanes = 0;
    private int cantCafe = 0;
    private int cantTe = 0;
    private int cantJbns = 0;
    private int cantBisu = 0;
    /**
     * Creates new form PantallaPedido
     */
    public PantallaPedido(Producto[] tienda) {
        initComponents();
        this.tienda = tienda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        entregarPedido = new javax.swing.JButton();
        panelPie = new javax.swing.JPanel();
        pieMenosBtn = new javax.swing.JButton();
        pieMasBtn = new javax.swing.JButton();
        jPanelnum = new javax.swing.JPanel();
        pieCont = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        pieLbl = new javax.swing.JLabel();
        piePng1 = new javax.swing.JLabel();
        panelPan = new javax.swing.JPanel();
        panMenosBtn = new javax.swing.JButton();
        panMasBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        panCont = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        panLbl = new javax.swing.JLabel();
        panPng = new javax.swing.JLabel();
        panelPinia = new javax.swing.JPanel();
        piniaMenosBtn = new javax.swing.JButton();
        piniaMasBtn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        piniaCont = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        piniaLbl = new javax.swing.JLabel();
        piniaPng = new javax.swing.JLabel();
        panelGomitas = new javax.swing.JPanel();
        gomMenosBtn = new javax.swing.JButton();
        gomMasBtn = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        gomCont = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        gomsLbl = new javax.swing.JLabel();
        gomitasPng = new javax.swing.JLabel();
        panelBisu = new javax.swing.JPanel();
        bisuMenosBtn = new javax.swing.JButton();
        bisuMasBtn = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        bisuCont = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        bisuLbl = new javax.swing.JLabel();
        bisuPng = new javax.swing.JLabel();
        panelJabones = new javax.swing.JPanel();
        jabMenosBtn = new javax.swing.JButton();
        jabMasBtn = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jabonCont = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jabonLbl = new javax.swing.JLabel();
        jabonPng = new javax.swing.JLabel();
        panelTe = new javax.swing.JPanel();
        teMenosBtn = new javax.swing.JButton();
        teMasBtn = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        teCont = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        teLbl = new javax.swing.JLabel();
        tePng = new javax.swing.JLabel();
        panelCafe = new javax.swing.JPanel();
        cafeMenosBtn = new javax.swing.JButton();
        cafeMasBtn = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        cafeCont = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        cafeLbl = new javax.swing.JLabel();
        cafePng = new javax.swing.JLabel();

        nextCliente.setBackground(new java.awt.Color(60, 1, 1));
        nextCliente.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        nextCliente.setForeground(new java.awt.Color(255, 255, 204));
        nextCliente.setText("Siguiente Cliente>>");
        nextCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextClienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entregarPedido.setBackground(new java.awt.Color(60, 1, 1));
        entregarPedido.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        entregarPedido.setForeground(new java.awt.Color(255, 255, 204));
        entregarPedido.setText("Entregar >>");
        entregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(entregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 50));

        panelPie.setBackground(new java.awt.Color(253, 202, 51));
        panelPie.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelPie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pieMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        pieMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        pieMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        pieMenosBtn.setText("-");
        pieMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieMenosBtnActionPerformed(evt);
            }
        });
        panelPie.add(pieMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        pieMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        pieMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        pieMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        pieMasBtn.setText("+");
        pieMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieMasBtnActionPerformed(evt);
            }
        });
        panelPie.add(pieMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanelnum.setBackground(new java.awt.Color(145, 216, 200));
        jPanelnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pieCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        pieCont.setForeground(new java.awt.Color(0, 0, 0));
        pieCont.setText("0");

        javax.swing.GroupLayout jPanelnumLayout = new javax.swing.GroupLayout(jPanelnum);
        jPanelnum.setLayout(jPanelnumLayout);
        jPanelnumLayout.setHorizontalGroup(
            jPanelnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelnumLayout.createSequentialGroup()
                .addComponent(pieCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelnumLayout.setVerticalGroup(
            jPanelnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelnumLayout.createSequentialGroup()
                .addComponent(pieCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelPie.add(jPanelnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel11.setBackground(new java.awt.Color(145, 216, 200));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pieLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        pieLbl.setForeground(new java.awt.Color(0, 0, 0));
        pieLbl.setText("Pie de Limon");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(pieLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelPie.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        piePng1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/pie de limon.jpeg"))); // NOI18N
        piePng1.setText("jLabel17");
        panelPie.add(piePng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 170));

        panelPan.setBackground(new java.awt.Color(253, 202, 51));
        panelPan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        panMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        panMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        panMenosBtn.setText("-");
        panMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panMenosBtnActionPerformed(evt);
            }
        });
        panelPan.add(panMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        panMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        panMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        panMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        panMasBtn.setText("+");
        panMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panMasBtnActionPerformed(evt);
            }
        });
        panelPan.add(panMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel12.setBackground(new java.awt.Color(145, 216, 200));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        panCont.setForeground(new java.awt.Color(0, 0, 0));
        panCont.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(panCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(panCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelPan.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel13.setBackground(new java.awt.Color(145, 216, 200));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        panLbl.setForeground(new java.awt.Color(0, 0, 0));
        panLbl.setText("Pan de Minimo");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(panLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelPan.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        panPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/pan (1).jpg"))); // NOI18N
        panPng.setText("jLabel17");
        panelPan.add(panPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 160, 170));

        panelPinia.setBackground(new java.awt.Color(253, 202, 51));
        panelPinia.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelPinia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        piniaMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        piniaMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        piniaMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        piniaMenosBtn.setText("-");
        piniaMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piniaMenosBtnActionPerformed(evt);
            }
        });
        panelPinia.add(piniaMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        piniaMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        piniaMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        piniaMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        piniaMasBtn.setText("+");
        piniaMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piniaMasBtnActionPerformed(evt);
            }
        });
        panelPinia.add(piniaMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel14.setBackground(new java.awt.Color(145, 216, 200));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        piniaCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        piniaCont.setForeground(new java.awt.Color(0, 0, 0));
        piniaCont.setText("0");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(piniaCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(piniaCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelPinia.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel15.setBackground(new java.awt.Color(145, 216, 200));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        piniaLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        piniaLbl.setForeground(new java.awt.Color(0, 0, 0));
        piniaLbl.setText("Mini Pinia Loca");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(piniaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(piniaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelPinia.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        piniaPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/pinia loca.png"))); // NOI18N
        piniaPng.setText("jLabel17");
        panelPinia.add(piniaPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelPinia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, 170));

        panelGomitas.setBackground(new java.awt.Color(253, 202, 51));
        panelGomitas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelGomitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gomMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        gomMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        gomMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        gomMenosBtn.setText("-");
        gomMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gomMenosBtnActionPerformed(evt);
            }
        });
        panelGomitas.add(gomMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        gomMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        gomMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        gomMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        gomMasBtn.setText("+");
        gomMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gomMasBtnActionPerformed(evt);
            }
        });
        panelGomitas.add(gomMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel16.setBackground(new java.awt.Color(145, 216, 200));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gomCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        gomCont.setForeground(new java.awt.Color(0, 0, 0));
        gomCont.setText("0");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(gomCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(gomCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelGomitas.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel17.setBackground(new java.awt.Color(145, 216, 200));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gomsLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        gomsLbl.setForeground(new java.awt.Color(0, 0, 0));
        gomsLbl.setText("Gomitas Enchiladas");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gomsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(gomsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelGomitas.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        gomitasPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/gomitas.png"))); // NOI18N
        gomitasPng.setText("jLabel17");
        panelGomitas.add(gomitasPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelGomitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 160, 170));

        panelBisu.setBackground(new java.awt.Color(253, 202, 51));
        panelBisu.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelBisu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bisuMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        bisuMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        bisuMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        bisuMenosBtn.setText("-");
        bisuMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisuMenosBtnActionPerformed(evt);
            }
        });
        panelBisu.add(bisuMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        bisuMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        bisuMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        bisuMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        bisuMasBtn.setText("+");
        bisuMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisuMasBtnActionPerformed(evt);
            }
        });
        panelBisu.add(bisuMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel18.setBackground(new java.awt.Color(145, 216, 200));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bisuCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        bisuCont.setForeground(new java.awt.Color(0, 0, 0));
        bisuCont.setText("0");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(bisuCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(bisuCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelBisu.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel19.setBackground(new java.awt.Color(145, 216, 200));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bisuLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        bisuLbl.setForeground(new java.awt.Color(0, 0, 0));
        bisuLbl.setText("Bisuteria");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bisuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(bisuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelBisu.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        bisuPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/bisuteria.png"))); // NOI18N
        bisuPng.setText("jLabel17");
        panelBisu.add(bisuPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelBisu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 170));

        panelJabones.setBackground(new java.awt.Color(253, 202, 51));
        panelJabones.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelJabones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jabMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        jabMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jabMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        jabMenosBtn.setText("-");
        jabMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabMenosBtnActionPerformed(evt);
            }
        });
        panelJabones.add(jabMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        jabMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        jabMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jabMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        jabMasBtn.setText("+");
        jabMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabMasBtnActionPerformed(evt);
            }
        });
        panelJabones.add(jabMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel20.setBackground(new java.awt.Color(145, 216, 200));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jabonCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jabonCont.setForeground(new java.awt.Color(0, 0, 0));
        jabonCont.setText("0");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jabonCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jabonCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelJabones.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel21.setBackground(new java.awt.Color(145, 216, 200));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jabonLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jabonLbl.setForeground(new java.awt.Color(0, 0, 0));
        jabonLbl.setText("Jabones Artesanales");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jabonLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jabonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelJabones.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        jabonPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/jabones.png"))); // NOI18N
        jabonPng.setText("jLabel17");
        panelJabones.add(jabonPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelJabones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 160, 170));

        panelTe.setBackground(new java.awt.Color(253, 202, 51));
        panelTe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelTe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        teMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        teMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        teMenosBtn.setText("-");
        teMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teMenosBtnActionPerformed(evt);
            }
        });
        panelTe.add(teMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        teMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        teMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        teMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        teMasBtn.setText("+");
        teMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teMasBtnActionPerformed(evt);
            }
        });
        panelTe.add(teMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel22.setBackground(new java.awt.Color(145, 216, 200));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        teCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        teCont.setForeground(new java.awt.Color(0, 0, 0));
        teCont.setText("0");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(teCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(teCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelTe.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel23.setBackground(new java.awt.Color(145, 216, 200));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        teLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        teLbl.setForeground(new java.awt.Color(0, 0, 0));
        teLbl.setText("Te Frio");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(teLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelTe.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        tePng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/te frio.png"))); // NOI18N
        tePng.setText("jLabel17");
        panelTe.add(tePng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelTe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 160, 170));

        panelCafe.setBackground(new java.awt.Color(253, 202, 51));
        panelCafe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelCafe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cafeMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        cafeMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        cafeMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        cafeMenosBtn.setText("-");
        cafeMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeMenosBtnActionPerformed(evt);
            }
        });
        panelCafe.add(cafeMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        cafeMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        cafeMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        cafeMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        cafeMasBtn.setText("+");
        cafeMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeMasBtnActionPerformed(evt);
            }
        });
        panelCafe.add(cafeMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel24.setBackground(new java.awt.Color(145, 216, 200));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cafeCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        cafeCont.setForeground(new java.awt.Color(0, 0, 0));
        cafeCont.setText("0");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(cafeCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(cafeCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelCafe.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel25.setBackground(new java.awt.Color(145, 216, 200));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cafeLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        cafeLbl.setForeground(new java.awt.Color(0, 0, 0));
        cafeLbl.setText("Cafe");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cafeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(cafeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelCafe.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        cafePng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/cafe.png"))); // NOI18N
        cafePng.setText("jLabel17");
        panelCafe.add(cafePng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 160, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextClienteActionPerformed
        
    }//GEN-LAST:event_nextClienteActionPerformed

    private void entregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarPedidoActionPerformed
        if (cantPies > 0){
            cantidades.add(cantPies);
        }
    }//GEN-LAST:event_entregarPedidoActionPerformed

    private void pieMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieMasBtnActionPerformed
        cantPies = añadirCant(cantPies);
        cantidades(cantPies, pieCont);
    }//GEN-LAST:event_pieMasBtnActionPerformed

    private void pieMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieMenosBtnActionPerformed
        cantPies = restarCant(cantPies);
        cantidades(cantPies, pieCont);
    }//GEN-LAST:event_pieMenosBtnActionPerformed

    private void piniaMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piniaMasBtnActionPerformed
        cantPinias = añadirCant(cantPinias);
        cantidades(cantPinias, piniaCont);
    }//GEN-LAST:event_piniaMasBtnActionPerformed

    private void piniaMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piniaMenosBtnActionPerformed
        cantPinias = restarCant(cantPinias);
        cantidades(cantPinias, piniaCont);
    }//GEN-LAST:event_piniaMenosBtnActionPerformed

    private void gomMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gomMasBtnActionPerformed
        cantGoms = añadirCant(cantGoms);
        cantidades(cantGoms, gomCont);
    }//GEN-LAST:event_gomMasBtnActionPerformed

    private void gomMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gomMenosBtnActionPerformed
        cantGoms = restarCant(cantGoms);
        cantidades(cantGoms, gomCont);
    }//GEN-LAST:event_gomMenosBtnActionPerformed

    private void panMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panMasBtnActionPerformed
        cantPanes = añadirCant(cantPanes);
        cantidades(cantPanes, panCont);
    }//GEN-LAST:event_panMasBtnActionPerformed

    private void panMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panMenosBtnActionPerformed
        cantPanes = restarCant(cantPanes);
        cantidades(cantPanes, panCont);
    }//GEN-LAST:event_panMenosBtnActionPerformed

    private void cafeMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeMasBtnActionPerformed
        cantCafe = añadirCant(cantCafe);
        cantidades(cantCafe, cafeCont);
    }//GEN-LAST:event_cafeMasBtnActionPerformed

    private void cafeMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeMenosBtnActionPerformed
        cantCafe = restarCant(cantCafe);
        cantidades(cantCafe, cafeCont);
    }//GEN-LAST:event_cafeMenosBtnActionPerformed

    private void teMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teMasBtnActionPerformed
        cantTe = añadirCant(cantTe);
        cantidades(cantTe, teCont);
    }//GEN-LAST:event_teMasBtnActionPerformed

    private void teMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teMenosBtnActionPerformed
        cantTe = restarCant(cantTe);
        cantidades(cantTe, teCont);
    }//GEN-LAST:event_teMenosBtnActionPerformed

    private void jabMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabMasBtnActionPerformed
        cantJbns = añadirCant(cantJbns);
        cantidades(cantJbns, jabonCont);
    }//GEN-LAST:event_jabMasBtnActionPerformed

    private void jabMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabMenosBtnActionPerformed
        cantJbns = restarCant(cantJbns);
        cantidades(cantJbns, jabonCont);
    }//GEN-LAST:event_jabMenosBtnActionPerformed

    private void bisuMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisuMasBtnActionPerformed
        cantBisu = añadirCant(cantBisu);
        cantidades(cantBisu, bisuCont);
    }//GEN-LAST:event_bisuMasBtnActionPerformed

    private void bisuMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisuMenosBtnActionPerformed
        cantBisu = restarCant(cantBisu);
        cantidades(cantBisu, bisuCont);
    }//GEN-LAST:event_bisuMenosBtnActionPerformed

    public void cantidades (int cant, JLabel label){
        String cantidad = Integer.toString(cant);
        label.setText(cantidad);
    }
    
    public int añadirCant (int cant){
        return cant + 1;
    }
    
    public int restarCant (int cant){
        if (cant > 0){
            return cant - 1;
        }
        return cant;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bisuCont;
    private javax.swing.JLabel bisuLbl;
    private javax.swing.JButton bisuMasBtn;
    private javax.swing.JButton bisuMenosBtn;
    private javax.swing.JLabel bisuPng;
    private javax.swing.JLabel cafeCont;
    private javax.swing.JLabel cafeLbl;
    private javax.swing.JButton cafeMasBtn;
    private javax.swing.JButton cafeMenosBtn;
    private javax.swing.JLabel cafePng;
    private javax.swing.JButton entregarPedido;
    private javax.swing.JLabel gomCont;
    private javax.swing.JButton gomMasBtn;
    private javax.swing.JButton gomMenosBtn;
    private javax.swing.JLabel gomitasPng;
    private javax.swing.JLabel gomsLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanelnum;
    private javax.swing.JButton jabMasBtn;
    private javax.swing.JButton jabMenosBtn;
    private javax.swing.JLabel jabonCont;
    private javax.swing.JLabel jabonLbl;
    private javax.swing.JLabel jabonPng;
    private javax.swing.JButton nextCliente;
    private javax.swing.JLabel panCont;
    private javax.swing.JLabel panLbl;
    private javax.swing.JButton panMasBtn;
    private javax.swing.JButton panMenosBtn;
    private javax.swing.JLabel panPng;
    private javax.swing.JPanel panelBisu;
    private javax.swing.JPanel panelCafe;
    private javax.swing.JPanel panelGomitas;
    private javax.swing.JPanel panelJabones;
    private javax.swing.JPanel panelPan;
    private javax.swing.JPanel panelPie;
    private javax.swing.JPanel panelPinia;
    private javax.swing.JPanel panelTe;
    private javax.swing.JLabel pieCont;
    private javax.swing.JLabel pieLbl;
    private javax.swing.JButton pieMasBtn;
    private javax.swing.JButton pieMenosBtn;
    private javax.swing.JLabel piePng1;
    private javax.swing.JLabel piniaCont;
    private javax.swing.JLabel piniaLbl;
    private javax.swing.JButton piniaMasBtn;
    private javax.swing.JButton piniaMenosBtn;
    private javax.swing.JLabel piniaPng;
    private javax.swing.JLabel teCont;
    private javax.swing.JLabel teLbl;
    private javax.swing.JButton teMasBtn;
    private javax.swing.JButton teMenosBtn;
    private javax.swing.JLabel tePng;
    // End of variables declaration//GEN-END:variables
}
