/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minitienda_isabelladubon.GUI;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import minitienda_isabelladubon.Factura;
import minitienda_isabelladubon.GestorPedido;
import minitienda_isabelladubon.Pedido;
import minitienda_isabelladubon.Producto;
import minitienda_isabelladubon.Usuario;

/**
 *
 * @author miria
 */
public class PantallaPedido extends javax.swing.JPanel {
    private Producto[] tienda;
    private GestorPedido gestor;
    private Main mainFrame;
    private int cantPies = 0;
    private int cantPinias = 0;
    private int cantGoms = 0;
    private int cantPanes = 0;
    private int cantCafe = 0;
    private int cantTe = 0;
    private int cantJbns = 0;
    private int cantBisu = 0;
    private String pedido = "";
    private int numPedido;
    private PantallaMain principal;
    Producto pie;
    Producto pinia;
    Producto gomitas;
    Producto pan;
    Producto cafe;
    Producto te;
    Producto jabon;
    Producto bisu;
    private final Usuario seleccion;
    private Pedido pedidoActual;
    /**
     * Creates new form PantallaPedido
     */
    
    public PantallaPedido(Producto[] tienda, Usuario seleccion, PantallaMain principal, Main mainFrame) {
        initComponents();
        this.tienda = tienda;
        this.seleccion = seleccion;
        this.principal = principal;
        this.mainFrame = mainFrame;
        pie = tienda[0];
        pinia = tienda[1];
        gomitas = tienda[2];
        pan = tienda[3];
        te = tienda[4];
        cafe = tienda[5];
        jabon = tienda[6];
        bisu = tienda[7];
        this.resetNuevoCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        entregarPedido = new javax.swing.JButton();
        panelPie = new javax.swing.JPanel();
        pieMenosBtn = new javax.swing.JButton();
        pieMasBtn = new javax.swing.JButton();
        jPanelnum = new javax.swing.JPanel();
        pieCont = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        pieLbl = new javax.swing.JLabel();
        piePng1 = new javax.swing.JLabel();
        panelPan = new javax.swing.JPanel();
        panMenosBtn = new javax.swing.JButton();
        panMasBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        panCont = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        panLbl = new javax.swing.JLabel();
        panPng = new javax.swing.JLabel();
        panelPinia = new javax.swing.JPanel();
        piniaMenosBtn = new javax.swing.JButton();
        piniaMasBtn = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        piniaCont = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        piniaLbl = new javax.swing.JLabel();
        piniaPng = new javax.swing.JLabel();
        panelGomitas = new javax.swing.JPanel();
        gomMenosBtn = new javax.swing.JButton();
        gomMasBtn = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        gomCont = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        gomsLbl = new javax.swing.JLabel();
        gomitasPng = new javax.swing.JLabel();
        panelBisu = new javax.swing.JPanel();
        bisuMenosBtn = new javax.swing.JButton();
        bisuMasBtn = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        bisuCont = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        bisuLbl = new javax.swing.JLabel();
        bisuPng = new javax.swing.JLabel();
        panelJabones = new javax.swing.JPanel();
        jabMenosBtn = new javax.swing.JButton();
        jabMasBtn = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jabonCont = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jabonLbl = new javax.swing.JLabel();
        jabonPng = new javax.swing.JLabel();
        panelTe = new javax.swing.JPanel();
        teMenosBtn = new javax.swing.JButton();
        teMasBtn = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        teCont = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        teLbl = new javax.swing.JLabel();
        tePng = new javax.swing.JLabel();
        panelCafe = new javax.swing.JPanel();
        cafeMenosBtn = new javax.swing.JButton();
        cafeMasBtn = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        cafeCont = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        cafeLbl = new javax.swing.JLabel();
        cafePng = new javax.swing.JLabel();

        nextCliente.setBackground(new java.awt.Color(60, 1, 1));
        nextCliente.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        nextCliente.setForeground(new java.awt.Color(255, 255, 204));
        nextCliente.setText("Siguiente Cliente>>");
        nextCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextClienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entregarPedido.setBackground(new java.awt.Color(60, 1, 1));
        entregarPedido.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        entregarPedido.setForeground(new java.awt.Color(255, 255, 204));
        entregarPedido.setText("Entregar >>");
        entregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(entregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 50));

        panelPie.setBackground(new java.awt.Color(253, 202, 51));
        panelPie.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelPie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pieMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        pieMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        pieMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        pieMenosBtn.setText("-");
        pieMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieMenosBtnActionPerformed(evt);
            }
        });
        panelPie.add(pieMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        pieMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        pieMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        pieMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        pieMasBtn.setText("+");
        pieMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieMasBtnActionPerformed(evt);
            }
        });
        panelPie.add(pieMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanelnum.setBackground(new java.awt.Color(145, 216, 200));
        jPanelnum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pieCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        pieCont.setForeground(new java.awt.Color(0, 0, 0));
        pieCont.setText("0");

        javax.swing.GroupLayout jPanelnumLayout = new javax.swing.GroupLayout(jPanelnum);
        jPanelnum.setLayout(jPanelnumLayout);
        jPanelnumLayout.setHorizontalGroup(
            jPanelnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelnumLayout.createSequentialGroup()
                .addComponent(pieCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelnumLayout.setVerticalGroup(
            jPanelnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelnumLayout.createSequentialGroup()
                .addComponent(pieCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelPie.add(jPanelnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel11.setBackground(new java.awt.Color(145, 216, 200));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pieLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        pieLbl.setForeground(new java.awt.Color(0, 0, 0));
        pieLbl.setText("Pie de Limon L.40");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(pieLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelPie.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        piePng1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/pie de limon.jpeg"))); // NOI18N
        piePng1.setText("jLabel17");
        panelPie.add(piePng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 170));

        panelPan.setBackground(new java.awt.Color(253, 202, 51));
        panelPan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        panMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        panMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        panMenosBtn.setText("-");
        panMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panMenosBtnActionPerformed(evt);
            }
        });
        panelPan.add(panMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        panMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        panMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        panMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        panMasBtn.setText("+");
        panMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panMasBtnActionPerformed(evt);
            }
        });
        panelPan.add(panMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel12.setBackground(new java.awt.Color(145, 216, 200));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        panCont.setForeground(new java.awt.Color(0, 0, 0));
        panCont.setText("0");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(panCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(panCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelPan.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel13.setBackground(new java.awt.Color(145, 216, 200));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        panLbl.setForeground(new java.awt.Color(0, 0, 0));
        panLbl.setText("Pan de Minimo L.35");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(panLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelPan.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        panPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/pan (1).jpg"))); // NOI18N
        panPng.setText("jLabel17");
        panelPan.add(panPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 160, 170));

        panelPinia.setBackground(new java.awt.Color(253, 202, 51));
        panelPinia.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelPinia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        piniaMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        piniaMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        piniaMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        piniaMenosBtn.setText("-");
        piniaMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piniaMenosBtnActionPerformed(evt);
            }
        });
        panelPinia.add(piniaMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        piniaMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        piniaMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        piniaMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        piniaMasBtn.setText("+");
        piniaMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piniaMasBtnActionPerformed(evt);
            }
        });
        panelPinia.add(piniaMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel14.setBackground(new java.awt.Color(145, 216, 200));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        piniaCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        piniaCont.setForeground(new java.awt.Color(0, 0, 0));
        piniaCont.setText("0");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(piniaCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(piniaCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelPinia.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel15.setBackground(new java.awt.Color(145, 216, 200));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        piniaLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        piniaLbl.setForeground(new java.awt.Color(0, 0, 0));
        piniaLbl.setText("Mini Piña Loca l.25");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(piniaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(piniaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelPinia.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        piniaPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/pinia loca.png"))); // NOI18N
        piniaPng.setText("jLabel17");
        panelPinia.add(piniaPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelPinia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, 170));

        panelGomitas.setBackground(new java.awt.Color(253, 202, 51));
        panelGomitas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelGomitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gomMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        gomMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        gomMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        gomMenosBtn.setText("-");
        gomMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gomMenosBtnActionPerformed(evt);
            }
        });
        panelGomitas.add(gomMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        gomMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        gomMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        gomMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        gomMasBtn.setText("+");
        gomMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gomMasBtnActionPerformed(evt);
            }
        });
        panelGomitas.add(gomMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel16.setBackground(new java.awt.Color(145, 216, 200));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gomCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        gomCont.setForeground(new java.awt.Color(0, 0, 0));
        gomCont.setText("0");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(gomCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(gomCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelGomitas.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel17.setBackground(new java.awt.Color(145, 216, 200));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gomsLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 11)); // NOI18N
        gomsLbl.setForeground(new java.awt.Color(0, 0, 0));
        gomsLbl.setText("Gomitas Enchiladas L.20");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gomsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(gomsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelGomitas.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        gomitasPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/gomitas.png"))); // NOI18N
        gomitasPng.setText("jLabel17");
        panelGomitas.add(gomitasPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelGomitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 160, 170));

        panelBisu.setBackground(new java.awt.Color(253, 202, 51));
        panelBisu.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelBisu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bisuMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        bisuMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        bisuMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        bisuMenosBtn.setText("-");
        bisuMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisuMenosBtnActionPerformed(evt);
            }
        });
        panelBisu.add(bisuMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        bisuMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        bisuMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        bisuMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        bisuMasBtn.setText("+");
        bisuMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bisuMasBtnActionPerformed(evt);
            }
        });
        panelBisu.add(bisuMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel18.setBackground(new java.awt.Color(145, 216, 200));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bisuCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        bisuCont.setForeground(new java.awt.Color(0, 0, 0));
        bisuCont.setText("0");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(bisuCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(bisuCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelBisu.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel19.setBackground(new java.awt.Color(145, 216, 200));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bisuLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        bisuLbl.setForeground(new java.awt.Color(0, 0, 0));
        bisuLbl.setText("Bisuteria L.25");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bisuLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(bisuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelBisu.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        bisuPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/bisuteria.png"))); // NOI18N
        bisuPng.setText("jLabel17");
        panelBisu.add(bisuPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelBisu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 170));

        panelJabones.setBackground(new java.awt.Color(253, 202, 51));
        panelJabones.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelJabones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jabMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        jabMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jabMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        jabMenosBtn.setText("-");
        jabMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabMenosBtnActionPerformed(evt);
            }
        });
        panelJabones.add(jabMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        jabMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        jabMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jabMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        jabMasBtn.setText("+");
        jabMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabMasBtnActionPerformed(evt);
            }
        });
        panelJabones.add(jabMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel20.setBackground(new java.awt.Color(145, 216, 200));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jabonCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jabonCont.setForeground(new java.awt.Color(0, 0, 0));
        jabonCont.setText("0");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jabonCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jabonCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelJabones.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel21.setBackground(new java.awt.Color(145, 216, 200));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jabonLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 11)); // NOI18N
        jabonLbl.setForeground(new java.awt.Color(0, 0, 0));
        jabonLbl.setText("Jabones Artesanales L.60");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jabonLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jabonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelJabones.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        jabonPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/jabones.png"))); // NOI18N
        jabonPng.setText("jLabel17");
        panelJabones.add(jabonPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelJabones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 160, 170));

        panelTe.setBackground(new java.awt.Color(253, 202, 51));
        panelTe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelTe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        teMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        teMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        teMenosBtn.setText("-");
        teMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teMenosBtnActionPerformed(evt);
            }
        });
        panelTe.add(teMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        teMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        teMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        teMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        teMasBtn.setText("+");
        teMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teMasBtnActionPerformed(evt);
            }
        });
        panelTe.add(teMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel22.setBackground(new java.awt.Color(145, 216, 200));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        teCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        teCont.setForeground(new java.awt.Color(0, 0, 0));
        teCont.setText("0");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(teCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(teCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelTe.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel23.setBackground(new java.awt.Color(145, 216, 200));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        teLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        teLbl.setForeground(new java.awt.Color(0, 0, 0));
        teLbl.setText("Te Frio L.20");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(teLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelTe.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        tePng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/te frio.png"))); // NOI18N
        tePng.setText("jLabel17");
        panelTe.add(tePng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelTe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 160, 170));

        panelCafe.setBackground(new java.awt.Color(253, 202, 51));
        panelCafe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        panelCafe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cafeMenosBtn.setBackground(new java.awt.Color(60, 1, 1));
        cafeMenosBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        cafeMenosBtn.setForeground(new java.awt.Color(255, 255, 204));
        cafeMenosBtn.setText("-");
        cafeMenosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeMenosBtnActionPerformed(evt);
            }
        });
        panelCafe.add(cafeMenosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 43, 40));

        cafeMasBtn.setBackground(new java.awt.Color(60, 1, 1));
        cafeMasBtn.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        cafeMasBtn.setForeground(new java.awt.Color(255, 255, 204));
        cafeMasBtn.setText("+");
        cafeMasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeMasBtnActionPerformed(evt);
            }
        });
        panelCafe.add(cafeMasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 43, 40));

        jPanel24.setBackground(new java.awt.Color(145, 216, 200));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cafeCont.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        cafeCont.setForeground(new java.awt.Color(0, 0, 0));
        cafeCont.setText("0");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(cafeCont, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(cafeCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        panelCafe.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jPanel25.setBackground(new java.awt.Color(145, 216, 200));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cafeLbl.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        cafeLbl.setForeground(new java.awt.Color(0, 0, 0));
        cafeLbl.setText("Cafe L.12");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cafeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(cafeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        panelCafe.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 170, -1));

        cafePng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/cafe.png"))); // NOI18N
        cafePng.setText("jLabel17");
        panelCafe.add(cafePng, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 120));

        jPanel1.add(panelCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 160, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextClienteActionPerformed
        
    }//GEN-LAST:event_nextClienteActionPerformed

    private void entregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarPedidoActionPerformed
        ArrayList<Producto> productos = new ArrayList<>();
        ArrayList<Integer> cantidades = new ArrayList<>();
        if (this.cantPies > 0){
            productos.add(this.pie);
            cantidades.add(this.cantPies);
            if (cantPies > tienda[0].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente stock de pies !! \n Stock: "+ tienda[0].getStock());
                return;
            }
        }
        if (this.cantPinias > 0){
            productos.add(this.pinia);
            cantidades.add(this.cantPinias);
            if (cantPinias > tienda[1].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente stock de piñas !! \n Stock: "+ tienda[1].getStock());
                return;
            }
        }
        if (this.cantGoms > 0){
            productos.add(this.gomitas);
            cantidades.add(this.cantGoms);
            if (cantGoms > tienda[2].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente stock de gomitas !! \n Stock: "+ tienda[2].getStock());
                return;
            }
        }
        if (this.cantPanes > 0){
            productos.add(this.pan);
            cantidades.add(this.cantPanes);
            if (cantPanes > tienda[3].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente stock de pan !! \n Stock: "+ tienda[3].getStock());
                return;
            }
        }
        if (this.cantCafe > 0){
            productos.add(this.cafe);
            cantidades.add(this.cantCafe);
            if (cantCafe > tienda[5].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente cafe !! \n Stock: "+ tienda[5].getStock());
                return;
            }
        }
        if (this.cantTe > 0){
            productos.add(this.te);
            cantidades.add(this.cantTe);
            if (cantTe > tienda[4].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente te frio !! \n Stock: "+ tienda[4].getStock());
                return;
            }
        }
        if (this.cantJbns > 0){
            productos.add(this.jabon);
            cantidades.add(this.cantJbns);
            if (cantJbns > tienda[6].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente stock de jabones !! \n Stock: "+ tienda[6].getStock());
                return;
            }
        }
        if (this.cantBisu > 0){
            productos.add(this.bisu);
            cantidades.add(this.cantBisu);
            if (cantBisu > tienda[7].getStock()){
                JOptionPane.showMessageDialog(this, "!! Insuficiente stock de pulseras !! \n Stock: "+ tienda[7].getStock());
                return;
            }
        }
        Pedido pedidoIngresado = new Pedido(productos, cantidades, numPedido);
        boolean correcto = gestor.validarEntrega(this.pedidoActual, pedidoIngresado);
        double totalProducto = 0;
        int cantProducto = 0;
        double total = calcularTotal(totalProducto, cantProducto, productos, cantidades);
        if (correcto) { //si el pedido es correcto, avanza al siguiente pedido, muestra el panel principal y actualiza el dinero ganado
            JOptionPane.showMessageDialog(this, "Pedido entregado correctamente!");
            int dia = seleccion.getDiaEnJuego();
            int numFactura = mainFrame.getNumPedido();
            Factura facturaNueva = new Factura(dia, numFactura, this.pedidoActual, total);
            seleccion.agregarFactura(facturaNueva);
            if (cantPies <= tienda[0].getStock() && cantPies > 0){
                tienda[0].setStock(tienda[0].getStock()-cantPies);
            }
            if (cantPinias <= tienda[0].getStock() && cantPinias > 0){
                tienda[1].setStock(tienda[1].getStock()-cantPinias);
            }
            if (cantGoms <= tienda[2].getStock() && cantGoms > 0){
                tienda[2].setStock(tienda[2].getStock()-cantGoms);
            }
            if (cantPanes <= tienda[3].getStock() && cantPanes > 0){
                tienda[3].setStock(tienda[3].getStock()-cantPanes);
            }
            if (cantCafe <= tienda[5].getStock() && cantCafe > 0){
                tienda[5].setStock(tienda[5].getStock()-cantCafe);
            }
            if (cantTe <= tienda[4].getStock() && cantTe > 0){
                tienda[4].setStock(tienda[4].getStock()-cantTe);
            }
            if (cantJbns <= tienda[6].getStock() && cantJbns > 0){
                tienda[6].setStock(tienda[6].getStock()-cantJbns);
            }
            if (cantBisu <= tienda[7].getStock() && cantBisu > 0){
                tienda[7].setStock(tienda[7].getStock()-cantBisu);
            }
            mainFrame.avanzarASiguienteCliente();
            seleccion.setDinero(seleccion.getDinero()+total);
            mainFrame.actualizarDinero();
            mainFrame.getBotonMain().setEnabled(true);
            mainFrame.MostrarPanel(principal);
        }else {//sino, avanza al siguiente pedido y muestra el panel principal
            JOptionPane.showMessageDialog(this, "Pedido incorrecto! Intenta de nuevo");
            resetNuevoCliente();
            return;
        }
        this.resetNuevoCliente();
        
        System.out.println();
        System.out.println("=====Stocks=====");
        System.out.println("Pie stock: "+tienda[0].getStock());
        System.out.println("Pinias stock: "+tienda[1].getStock());
        System.out.println("Gomitas stock: "+tienda[2].getStock());
        System.out.println("Pan stock: "+tienda[3].getStock());
        System.out.println("Te Frio stock: "+tienda[4].getStock());
        System.out.println("Cafe stock: "+tienda[5].getStock());
        System.out.println("Jabones stock: "+tienda[6].getStock());
        System.out.println("Pulseras stock: "+tienda[7].getStock());
    }//GEN-LAST:event_entregarPedidoActionPerformed

    private double calcularTotal(double totalProducto, int cantProducto, ArrayList<Producto> productos, ArrayList<Integer> cantidades){
        double total = 0;
        for (int i = 0; i < productos.size(); i++){
            totalProducto = productos.get(i).getPrecio();
            cantProducto = cantidades.get(i);
            total += totalProducto * cantProducto;
        }
        return total;
    }
    private void pieMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieMasBtnActionPerformed
        this.cantPies++;
        cantidades(this.cantPies, pieCont);
    }//GEN-LAST:event_pieMasBtnActionPerformed

    private void pieMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieMenosBtnActionPerformed
        if (this.cantPies > 0){
            this.cantPies--;
        }
        cantidades(this.cantPies, pieCont);
    }//GEN-LAST:event_pieMenosBtnActionPerformed

    private void piniaMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piniaMasBtnActionPerformed
        this.cantPinias++;
        cantidades(this.cantPinias, piniaCont);
    }//GEN-LAST:event_piniaMasBtnActionPerformed

    private void piniaMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piniaMenosBtnActionPerformed
        if (this.cantPinias > 0){
            this.cantPinias--;
        }
        cantidades(this.cantPinias, piniaCont);
    }//GEN-LAST:event_piniaMenosBtnActionPerformed

    private void gomMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gomMasBtnActionPerformed
        this.cantGoms++;
        cantidades(this.cantGoms, gomCont);
    }//GEN-LAST:event_gomMasBtnActionPerformed

    private void gomMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gomMenosBtnActionPerformed
        if (this.cantGoms > 0){
            this.cantGoms--;
        }
        cantidades(this.cantGoms, gomCont);
    }//GEN-LAST:event_gomMenosBtnActionPerformed

    private void panMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panMasBtnActionPerformed
        this.cantPanes++;
        cantidades(this.cantPanes, panCont);
    }//GEN-LAST:event_panMasBtnActionPerformed

    private void panMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panMenosBtnActionPerformed
        if (this.cantPanes > 0){
            this.cantPanes--;
        }
        cantidades(this.cantPanes, panCont);
    }//GEN-LAST:event_panMenosBtnActionPerformed

    private void cafeMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeMasBtnActionPerformed
        this.cantCafe++;
        cantidades(this.cantCafe, cafeCont);
    }//GEN-LAST:event_cafeMasBtnActionPerformed

    private void cafeMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeMenosBtnActionPerformed
        if (this.cantCafe > 0){
            this.cantCafe--;
        }
        cantidades(this.cantCafe, cafeCont);
    }//GEN-LAST:event_cafeMenosBtnActionPerformed

    private void teMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teMasBtnActionPerformed
        this.cantTe++;
        cantidades(this.cantTe, teCont);
    }//GEN-LAST:event_teMasBtnActionPerformed

    private void teMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teMenosBtnActionPerformed
        if (this.cantTe > 0){
            this.cantTe--;
        }
        cantidades(this.cantTe, teCont);
    }//GEN-LAST:event_teMenosBtnActionPerformed

    private void jabMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabMasBtnActionPerformed
        this.cantJbns++;
        cantidades(this.cantJbns, jabonCont);
    }//GEN-LAST:event_jabMasBtnActionPerformed

    private void jabMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabMenosBtnActionPerformed
        if (this.cantJbns > 0){
            this.cantJbns--;
        }
        cantidades(this.cantJbns, jabonCont);
    }//GEN-LAST:event_jabMenosBtnActionPerformed

    private void bisuMasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisuMasBtnActionPerformed
        this.cantBisu++;
        cantidades(this.cantBisu, bisuCont);
    }//GEN-LAST:event_bisuMasBtnActionPerformed

    private void bisuMenosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisuMenosBtnActionPerformed
        if (this.cantBisu > 0){
            this.cantBisu--;
        }
        cantidades(this.cantBisu, bisuCont);
    }//GEN-LAST:event_bisuMenosBtnActionPerformed

    public void cantidades (int cant, JLabel label){
        String cantidad = Integer.toString(cant);
        label.setText(cantidad);
    }
   
    public void setGestorPedidos(GestorPedido gestor) {
        this.gestor = gestor;
    }

    //setter para el Pedido (llamar a este metodo cuando haya un pedido nuevo)
    public void setPedido(Pedido pedido) {
        this.pedidoActual = pedido;
    }
    public void resetNuevoCliente() {
        this.cantPies = 0;
        this.cantPinias = 0;
        this.cantGoms = 0;
        this.cantPanes = 0;
        this.cantCafe = 0;
        this.cantTe = 0;
        this.cantJbns = 0;
        this.cantBisu = 0;
        this.pieCont.setText("0");
        this.piniaCont.setText("0");
        this.gomCont.setText("0");
        this.panCont.setText("0");
        this.cafeCont.setText("0");
        this.teCont.setText("0");
        this.jabonCont.setText("0");
        this.bisuCont.setText("0");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bisuCont;
    private javax.swing.JLabel bisuLbl;
    private javax.swing.JButton bisuMasBtn;
    private javax.swing.JButton bisuMenosBtn;
    private javax.swing.JLabel bisuPng;
    private javax.swing.JLabel cafeCont;
    private javax.swing.JLabel cafeLbl;
    private javax.swing.JButton cafeMasBtn;
    private javax.swing.JButton cafeMenosBtn;
    private javax.swing.JLabel cafePng;
    private javax.swing.JButton entregarPedido;
    private javax.swing.JLabel gomCont;
    private javax.swing.JButton gomMasBtn;
    private javax.swing.JButton gomMenosBtn;
    private javax.swing.JLabel gomitasPng;
    private javax.swing.JLabel gomsLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanelnum;
    private javax.swing.JButton jabMasBtn;
    private javax.swing.JButton jabMenosBtn;
    private javax.swing.JLabel jabonCont;
    private javax.swing.JLabel jabonLbl;
    private javax.swing.JLabel jabonPng;
    private javax.swing.JButton nextCliente;
    private javax.swing.JLabel panCont;
    private javax.swing.JLabel panLbl;
    private javax.swing.JButton panMasBtn;
    private javax.swing.JButton panMenosBtn;
    private javax.swing.JLabel panPng;
    private javax.swing.JPanel panelBisu;
    private javax.swing.JPanel panelCafe;
    private javax.swing.JPanel panelGomitas;
    private javax.swing.JPanel panelJabones;
    private javax.swing.JPanel panelPan;
    private javax.swing.JPanel panelPie;
    private javax.swing.JPanel panelPinia;
    private javax.swing.JPanel panelTe;
    private javax.swing.JLabel pieCont;
    private javax.swing.JLabel pieLbl;
    private javax.swing.JButton pieMasBtn;
    private javax.swing.JButton pieMenosBtn;
    private javax.swing.JLabel piePng1;
    private javax.swing.JLabel piniaCont;
    private javax.swing.JLabel piniaLbl;
    private javax.swing.JButton piniaMasBtn;
    private javax.swing.JButton piniaMenosBtn;
    private javax.swing.JLabel piniaPng;
    private javax.swing.JLabel teCont;
    private javax.swing.JLabel teLbl;
    private javax.swing.JButton teMasBtn;
    private javax.swing.JButton teMenosBtn;
    private javax.swing.JLabel tePng;
    // End of variables declaration//GEN-END:variables
}
