/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minitienda_isabelladubon.GUI;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import minitienda_isabelladubon.Factura;
import minitienda_isabelladubon.Producto;
import minitienda_isabelladubon.Usuario;

/**
 *
 * @author miria
 */
public class PantallaBusqueda extends javax.swing.JPanel {
    private DefaultListModel<String> modeloTienda = new DefaultListModel<>();
    private ArrayList<Factura> facturasUsuario = new ArrayList<>();
    private Usuario seleccion;
    private Producto[] tienda;
    /**
     * Creates new form PantallaBusqueda
     */
    public PantallaBusqueda(Usuario seleccion, Producto[] tienda) {
        initComponents();
        this.seleccion = seleccion;
        this.tienda = tienda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JList<>();
        buscarTiendaTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        comandos = new javax.swing.JLabel();
        comandos1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setBackground(new java.awt.Color(60, 1, 1));
        buscar.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 204));
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 110, 50));

        jScrollPane1.setBackground(new java.awt.Color(253, 202, 51));

        mostrar.setBackground(new java.awt.Color(253, 202, 51));
        mostrar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        mostrar.setForeground(new java.awt.Color(60, 1, 1));
        jScrollPane1.setViewportView(mostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, 280));

        buscarTiendaTxt.setBackground(new java.awt.Color(60, 1, 1));
        buscarTiendaTxt.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        buscarTiendaTxt.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.add(buscarTiendaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 40, 500, -1));

        jPanel2.setBackground(new java.awt.Color(211, 55, 49));

        comandos.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        comandos.setForeground(new java.awt.Color(60, 1, 1));
        comandos.setText("Comandos:");

        comandos1.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        comandos1.setForeground(new java.awt.Color(60, 1, 1));
        comandos1.setText("<html> Para buscar productos: <p> nombre=x <p> (x es el nombre del producto <p>o parte de el) <p><p> Para buscar facturas por dia: <p> diax <p> (x es el numero de dia) <p><p> Para revisar el historial de <p> pedidos del dia: <p> historial <p> (IMPORTANTE: Solo muestra el historial del mismo dia en el que se busca.)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comandos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comandos1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comandos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comandos1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 190, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        facturasUsuario = this.seleccion.getFacturas();
        String busqueda = buscarTiendaTxt.getText();
        if (busqueda.contains("dia")){ //si contiene "dia" (ej. "dia 1")
            modeloTienda.clear(); //borra la lista primero
            String copia = busqueda.replace("dia", "").trim(); //le quita "dia"
            try{
                int dia = Integer.parseInt(copia);
                boolean hayEnDiaX = false;
                for (int i = 0; i < facturasUsuario.size(); i++){
                    if (facturasUsuario.get(i).getDia() == dia){ //imprime las facturas del numero de dia ingresado
                        modeloTienda.addElement(facturasUsuario.get(i).toString());
                        hayEnDiaX = true;
                    }
                }
                
                if (!hayEnDiaX){
                    modeloTienda.addElement("No hay facturas.");
                }
                mostrar.setModel(modeloTienda);
                mostrar.revalidate();
                mostrar.repaint();
            }catch (NumberFormatException numero){ //si el formato falla
                        JOptionPane.showMessageDialog(this, "Formato invalido. Usa: 'dia1', 'dia2', etc.");
                    }
        }else if (busqueda.contains("nombre=")){
            modeloTienda.clear(); //borra la lista primero
            String copia = busqueda.replace("nombre=", "").trim(); //le quita "dia"
            Producto encontrado = buscarProducto(tienda, copia, 0);
            if (encontrado != null){
                modeloTienda.addElement(encontrado.toString());
            }else{
                modeloTienda.addElement("Producto no encontrado.");
            }
            mostrar.setModel(modeloTienda);
            mostrar.revalidate();
            mostrar.repaint();
        }else if(busqueda.equals("historial")){
            modeloTienda.clear();
            boolean[][] historial = this.seleccion.getHistorialPedidos();
            int total = this.seleccion.getIndicePedido();
    
            for (int i = 0; i < total; i++) {
                String simbolo;
                if (historial[i][0]) {
                    simbolo = "Correcto!";  //correcto
                } else {
                    simbolo = "Fallo!";  //incorrecto
                }
            modeloTienda.addElement("Pedido #" + (i+1) + ": " + simbolo);
            mostrar.setModel(modeloTienda);
            mostrar.revalidate();
            mostrar.repaint();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Formato invalido. Ej: 'nombre=Pie de Limon' || Usa: 'dia1', 'dia2', etc. || Usa: 'historial'");
        }
    }//GEN-LAST:event_buscarActionPerformed

    private Producto buscarProducto(Producto[] tienda, String nombre, int index){
        if (index >= tienda.length){
            return null;
        }
        if (tienda[index].getProducto().toLowerCase().trim().contains(nombre.toLowerCase().trim())){
            return tienda[index];
        }
        return buscarProducto(tienda,nombre,(index+1));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarTiendaTxt;
    private javax.swing.JLabel comandos;
    private javax.swing.JLabel comandos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> mostrar;
    // End of variables declaration//GEN-END:variables
}
