/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package minitienda_isabelladubon.GUI;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import java.util.Random;
import javax.swing.JOptionPane;
import minitienda_isabelladubon.Pedido;
import minitienda_isabelladubon.Producto;
import minitienda_isabelladubon.Usuario;

public class PantallaMain extends javax.swing.JPanel {
    Random random = new Random();
    private Producto[] tienda;
    private Usuario seleccion;
    private Main mainFrame;
    private boolean pedidoEntregado = true;
    private int numPedido;
    private Pedido pedidoActual;
    private int dia;
    /**
     * Creates new form PantallaMain
     */
    
    public PantallaMain(Producto[] tienda, Usuario seleccion, Main mainFrame) {
        initComponents();
        this.tienda = tienda;
        this.seleccion = seleccion;
        this.mainFrame = mainFrame;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pedidoClientePnl = new javax.swing.JPanel();
        pedidoLbl = new javax.swing.JLabel();
        PedidoLbl = new javax.swing.JLabel();
        pedidoNumLbl = new javax.swing.JLabel();
        nextDia = new javax.swing.JButton();
        stand = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pedidoClientePnl.setBackground(new java.awt.Color(211, 55, 49));
        pedidoClientePnl.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEtchedBorder()));

        pedidoLbl.setFont(new java.awt.Font("Bodoni MT Black", 1, 14)); // NOI18N
        pedidoLbl.setForeground(new java.awt.Color(0, 0, 0));
        pedidoLbl.setText("jLabel1");

        PedidoLbl.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        PedidoLbl.setForeground(new java.awt.Color(0, 0, 0));
        PedidoLbl.setText("Pedido");

        pedidoNumLbl.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        pedidoNumLbl.setForeground(new java.awt.Color(0, 0, 0));
        pedidoNumLbl.setText("1");

        javax.swing.GroupLayout pedidoClientePnlLayout = new javax.swing.GroupLayout(pedidoClientePnl);
        pedidoClientePnl.setLayout(pedidoClientePnlLayout);
        pedidoClientePnlLayout.setHorizontalGroup(
            pedidoClientePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pedidoClientePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pedidoClientePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pedidoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addGroup(pedidoClientePnlLayout.createSequentialGroup()
                        .addComponent(PedidoLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pedidoNumLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pedidoClientePnlLayout.setVerticalGroup(
            pedidoClientePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pedidoClientePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pedidoClientePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PedidoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidoNumLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pedidoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pedidoClientePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, 130));

        nextDia.setBackground(new java.awt.Color(60, 1, 1));
        nextDia.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        nextDia.setForeground(new java.awt.Color(255, 255, 204));
        nextDia.setText("Siguiente >>");
        nextDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextDiaActionPerformed(evt);
            }
        });
        jPanel1.add(nextDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, 50));

        stand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/Untitled4_20251209175549.png"))); // NOI18N
        jPanel1.add(stand, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 730, 450));

        cliente.setText("jLabel2");
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 220, 330));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/imageedit_2_8375449600.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextDiaActionPerformed
        nextDia.setVisible(false);
        mainFrame.actualizarDia();
        cliente.setVisible(true);
        PedidoLbl.setVisible(true);
        pedidoNumLbl.setVisible(false);
        mainFrame.MostrarPanel(this);
        mainFrame.avanzarASiguienteCliente();
        actualizarDisplay();
        JOptionPane.showMessageDialog(this, "Nuevo dia!");

    }//GEN-LAST:event_nextDiaActionPerformed

    public void setTienda(Producto[] tienda) {
        this.tienda = tienda;
    }

    public void setSeleccion(Usuario seleccion) {
        this.seleccion = seleccion;
    }

    public void alAbrirMain(){
        //genera un png de cliente random
        int numero = random.nextInt(1, 5);
        switch (numero){
            case 1:
                cliente.setIcon(new ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/cliente1.png")));
                break;
            case 2:
                cliente.setIcon(new ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/cliente2.png")));
                break;
            case 3:
                cliente.setIcon(new ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/cliente3.png")));
                break;
            case 4:
                cliente.setIcon(new ImageIcon(getClass().getResource("/minitienda_isabelladubon/Imags/cliente4.png")));
                break;
        }
        //imprime el pedido generado aleatoriamente
        numPedido = mainFrame.getNumPedido();
        this.actualizarDisplay();
        nextDia.setVisible(false);
    }
    //setter para el Pedido (llamar a este metodo cuando haya un pedido nuevo)
    public void setPedido(Pedido pedido) {
        this.pedidoActual = pedido;
        actualizarDisplay();
    }
    
    public void actualizarDisplay() {
        if (this.pedidoActual == null) {
            return;
        }
        String display = this.formatearPedido(this.pedidoActual);
        //actualizar el jlabel
        pedidoLbl.setText(display);
    }
    
    private String formatearPedido(Pedido pedido){
        if (pedido == null) {
            return "<html>Esperando pedido...</html>";
        }
        ArrayList<Producto> productos = pedido.getPedido();
        ArrayList<Integer> cantidades = pedido.getCantidades();

        String resultado = "<html>";
        for (int i = 0; i < productos.size(); i++) {
            int cantidad = cantidades.get(i);
            String nombreProducto = productos.get(i).getProducto();
            resultado += cantidad + " " + nombreProducto + "<br>"; 
        }

    resultado += "</html>";
    
    return resultado;
    }
    
    public javax.swing.JButton getBotonNextDia() {
        return this.nextDia; // Retorna la referencia al botón
    }
    
    public javax.swing.JLabel getLblCliente() {
        return this.cliente; // Retorna la referencia al cliente png
    }
    
    public javax.swing.JLabel getLblPedido() {
        return this.PedidoLbl; // Retorna la referencia al lbl "Pedido"
    }
    
    public javax.swing.JLabel getLblPedidoNum() {
        return this.pedidoNumLbl; // Retorna la referencia al lbl numero de pedido
    }
    
    public javax.swing.JLabel getLblPedidoDesc() {
        return this.pedidoLbl; // Retorna la referencia al lbl de la lista del pedido
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PedidoLbl;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextDia;
    private javax.swing.JPanel pedidoClientePnl;
    private javax.swing.JLabel pedidoLbl;
    private javax.swing.JLabel pedidoNumLbl;
    private javax.swing.JLabel stand;
    // End of variables declaration//GEN-END:variables
}
